export const TEST_DATA = {
  login: "Anveio",
  id: 8881711,
  node_id: "MDQ6VXNlcjg4ODE3MTE=",
  avatar_url: "https://avatars3.githubusercontent.com/u/8881711?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Anveio",
  html_url: "https://github.com/Anveio",
  followers_url: "https://api.github.com/users/Anveio/followers",
  following_url: "https://api.github.com/users/Anveio/following{/other_user}",
  gists_url: "https://api.github.com/users/Anveio/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Anveio/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Anveio/subscriptions",
  organizations_url: "https://api.github.com/users/Anveio/orgs",
  repos_url: "https://api.github.com/users/Anveio/repos",
  events_url: "https://api.github.com/users/Anveio/events{/privacy}",
  received_events_url: "https://api.github.com/users/Anveio/received_events",
  type: "User",
  site_admin: false,
  name: "Shovon Hasan",
  company: "Amazon",
  blog: "https://blog.shovonhasan.com",
  location: "Seattle, Washington",
  email: null,
  hireable: true,
  bio:
    "JavaScript dev. React + Redux + TypeScript = 💖. Creator of Mturk Engine.",
  twitter_username: null,
  public_repos: 30,
  public_gists: 3,
  followers: 21,
  following: 11,
  created_at: "2014-09-23T16:42:55Z",
  updated_at: "2020-08-30T22:17:05Z",
};
